#!/bin/bash

# version :type
function patch {
    local message=$1

    commit $message

    npm version patch

    local version=`radic-cli version`

    git push -u origin v${version}

    npm publish
}



$*